// =========================================================
// MediPredict — simple RULE-BASED scoring engine.
// This is NOT a trained machine learning model. It is a
// transparent if/else + weighted-scoring simulation so the
// app can demonstrate the "AI report" flow without a backend
// or a real model. Swap this file out if you later plug in
// a real ML/API-based prediction service.
// =========================================================

const CONDITION_RULES = [
    {
        name: "Common Cold / Flu",
        symptoms: ["fever", "cough", "soreThroat", "runnyNose", "fatigue", "headache"],
    },
    {
        name: "Migraine / Tension Headache",
        symptoms: ["headache", "dizziness", "nausea"],
    },
    {
        name: "Possible Diabetes Risk",
        symptoms: ["frequentUrination", "excessiveThirst", "blurredVision", "weightLoss", "fatigue"],
        bonus: (a) =>
            (a.existingConditions.includes("diabetes") ? 25 : 0) +
            (a.bloodSugar === "high" ? 20 : 0),
    },
    {
        name: "Hypertension / Cardiovascular Risk",
        symptoms: ["chestPain", "dizziness", "headache", "shortnessOfBreath"],
        bonus: (a) =>
            (a.existingConditions.includes("hypertension") ? 25 : 0) +
            (a.bloodPressure === "high" ? 20 : 0) +
            (a.smoking === "yes" ? 10 : 0),
    },
    {
        name: "Respiratory Concern",
        symptoms: ["cough", "shortnessOfBreath", "chestPain", "fever"],
        bonus: (a) => (a.existingConditions.includes("asthma") ? 20 : 0),
    },
    {
        name: "Stress / Sleep Imbalance",
        symptoms: ["fatigue", "headache"],
        bonus: (a) =>
            (a.stressLevel >= 7 ? 30 : 0) +
            (a.sleepHours <= 5 ? 25 : 0),
    },
];

function mpGeneratePrediction(a) {

    // ---- condition scoring ----
    const conditionScores = CONDITION_RULES.map((rule) => {
        const matched = rule.symptoms.filter((s) => a.symptoms.includes(s)).length;
        const base = rule.symptoms.length > 0 ? (matched / rule.symptoms.length) * 70 : 0;
        const bonus = rule.bonus ? rule.bonus(a) : 0;
        const percent = Math.min(100, Math.round(base + bonus));
        return { name: rule.name, percent };
    })
    .filter((c) => c.percent > 0)
    .sort((x, y) => y.percent - x.percent);

    const topConditions = conditionScores.slice(0, 3);
    const topPercent = topConditions.length > 0 ? topConditions[0].percent : 0;

    // ---- overall risk level ----
    let riskLevel = "Low";
    if (topPercent >= 60) riskLevel = "High";
    else if (topPercent >= 30) riskLevel = "Medium";

    // ---- lifestyle health score (0-100, higher = better) ----
    let healthScore = 100;

    if (a.smoking === "yes") healthScore -= 15;
    if (a.smoking === "occasionally") healthScore -= 7;

    if (a.alcohol === "frequent") healthScore -= 12;
    if (a.alcohol === "occasional") healthScore -= 5;

    if (a.activity === "sedentary") healthScore -= 15;
    if (a.activity === "light") healthScore -= 7;

    if (a.diet === "irregular") healthScore -= 12;
    if (a.diet === "highSugarFat") healthScore -= 10;

    if (a.sleepHours <= 5) healthScore -= 12;
    else if (a.sleepHours <= 6) healthScore -= 6;

    if (a.stressLevel >= 8) healthScore -= 12;
    else if (a.stressLevel >= 6) healthScore -= 6;

    healthScore -= a.symptoms.length * 2;
    healthScore -= a.existingConditions.filter((c) => c !== "none").length * 5;

    healthScore = Math.max(5, Math.min(100, Math.round(healthScore)));

    // ---- recommendations ----
    const recommendations = [];

    if (topConditions.length === 0) {
        recommendations.push("No significant symptom patterns detected — keep up your current routine.");
    } else {
        recommendations.push(`Consider discussing "${topConditions[0].name}" indicators with a doctor, especially if symptoms persist.`);
    }

    if (a.smoking === "yes") recommendations.push("Reducing or quitting smoking will meaningfully lower long-term health risks.");
    if (a.activity === "sedentary") recommendations.push("Aim for at least 20–30 minutes of light physical activity most days.");
    if (a.sleepHours <= 5) recommendations.push("Try to increase sleep to 7–8 hours a night — sleep debt affects both mood and immunity.");
    if (a.stressLevel >= 7) recommendations.push("High reported stress — breathing exercises, short walks, or talking to someone can help.");
    if (a.diet === "irregular" || a.diet === "highSugarFat") recommendations.push("A more consistent, balanced diet can improve several of the flagged risk areas.");
    if (a.bloodPressure === "high") recommendations.push("Since blood pressure was reported as high, regular monitoring is a good idea.");
    if (a.bloodSugar === "high") recommendations.push("Since blood sugar was reported as high, consider a follow-up check with a healthcare provider.");

    recommendations.push("This report is generated by simple rule-based logic in your browser, not a certified medical AI — always consult a qualified doctor for real diagnosis.");

    return {
        conditions: topConditions,
        topCondition: topConditions.length > 0 ? topConditions[0].name : "No Major Risk Flagged",
        riskLevel,
        healthScore,
        recommendations,
    };
}
